version: "3"
services:
  server:
    container_name: server
    build:
      context: ./sinatra-app
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9292:9292"
    volumes:
      - ./sinatra-app:/app
    command: "rackup --host 0.0.0.0 config.ru"
