* Agenda
bash, zsh, fish
RVM
RBENV
chruby
what is bundle exec
Docker, docker-compose, warm up project

* bundle exec
bundle exec is a Bundler command to execute a script in the context of the current bundle (the one from your directory's Gemfile). rake db:migrate is the script where db is the namespace and migrate is the task name defined.
So bundle exec rake db:migrate executes the rake script with the command db:migrate in the context of the current bundle.
As to the "why?" I'll quote from the bundler page:
In some cases, running executables without bundle exec may work, if the executable happens to be installed in your system and does not pull in any gems that conflict with your bundle.
However, this is unreliable and is the source of considerable pain. Even if it looks like it works, it may not work in the future or on another machine.
Bundler is a Ruby gem that’s a little special because it manages other Ruby gems. It does basically three things:
It does a topological sort of the gems listed in your Gemfile to print a complete graph of your project’s dependencies into Gemfile.lock
It retrieves the gems your project needs from the source(s) you’ve defined
And it makes it so when you require files the right file is loaded.

* rvm, rbenv
The two most popular Ruby version managers are RVM and rbenv (though I strongly recommend chruby). They work in totally different ways (RVM overwrites your cd shell builtin function!) but the output of all these tools is the same: They export environment variables so your Ruby code operates on a particular version of Ruby with a particular set of gems.
Here’s a diff[1] of the environment when we’re using one version of Ruby versus another:

